services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer_real_estate
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/000_init.sql
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: realEstate
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

volumes:
  mysql-data:

networks:
  internalnet:
    driver: bridge


    #docker-compose exec mysqldb mysql -u admin -p realEstate